name: Sample Ungen Action
on:
  workflow_dispatch:

jobs:
  ungen_job:
    runs-on: ubuntu-latest
    name: A job to run ungen
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Ungen action step
        uses: ./
        id: ungen
        with:
          inputDir: "examples/simple-nodejs"
          outputDir: "generated"
          keep: "false"
          ungenVersion: v0.2.1
          variables: |
            useTypescript=false
            appName="My New App"
            includeExtraFeature=false
      - name: Create GitHub Repo
        uses: howlowck/create-repo-action@v1.0
        with:
          zipPath: "generated.zip"
          repoName: "test-repo"
          repoDescription: "My repo description"
          repoVisibility: "private"
          securityToken: ${{ secrets.ORG_TOKEN }}

      - name: Get the output path
        run: echo "The path to output is ${{ steps.ungen.outputs.pathToOutput }}"
